To use and run tokenization using certain techniques:
1. Bag of Words : 

In [12]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'text':['people watch campusx', "campusx watch campusx", "people write comment", "campusx write comment"], 'output':[1,1,0,0]})

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [14]:
bow = cv.fit_transform(df['text'])
print(bow)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>
  Coords	Values
  (0, 2)	1
  (0, 3)	1
  (0, 0)	1
  (1, 3)	1
  (1, 0)	2
  (2, 2)	1
  (2, 4)	1
  (2, 1)	1
  (3, 0)	1
  (3, 4)	1
  (3, 1)	1


In [15]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]
[[0 1 1 0 1]]
[[1 1 0 0 1]]


In [17]:
cv.transform(["campusx watch write comment campusx to and well"]).toarray()

array([[2, 1, 0, 1, 1]])