In [2]:
import numpy as np

# creating array from list
arr_1d = np.array([1,2,3,4])
print("1D array :", arr_1d)
# np.array always and only takes 1 whole array inside 

arr_2d= np.array([[1,2,3],[3,4,5]])
print("2D array: ",arr_2d)

1D array : [1 2 3 4]
2D array:  [[1 2 3]
 [3 4 5]]



Element wise Multiplication

In [ ]:
py_list = [1,2,3]
print("Python list multiplied by 2: ", py_list*2)

np_array = np.array([1,2,3]) # elem wise mul
print("Python Numpy Array Mul: ", np_array*2)

import time

start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\nList Time Taken: ", time.time() - start)


start = time.time()
np_array = np.arange(10000000) * 2 #(start, stop(excluded), step)
print("\nArray Time Taken: ", time.time() - start)
#


Python list multiplied by 2:  [1, 2, 3, 1, 2, 3]
Python Numpy Array Mul:  [2 4 6]

List Time Taken:  0.46372151374816895

Array Time Taken:  0.05396747589111328


So from the above timing, we know that the operations on np.array are much faster 

# Creating Arrays From scratch in Numpy


- np.ones((m,n)), np.zeros((m,n)), np.full((m,n), k ), fills the matrix with specific values

- np.random: is noy a function, it is an entire class in itself:  

- in Python it is always non inclusive outer boundary
- np.arange(start, stop, step): it gives us a sequence array
  - np.arange(stop): starts from 0


In [3]:
zero = np.zeros((4,3))
print("\nZero array of 4*3", zero)

one = np.ones((5,4))
print("\nOne unit array of size 5*4", one)

specific_val_full= np.full((6,4), 5)
print("\array filled with 5 of size 6*4", specific_val_full)

random = np.random.random((2,3))
print("\n An Array filled with random values in between 0-1, of size 2*3", random)

sequence = np.arange(0,10,2)
print("\n Sequence array beginning from 0 to 10(excluded), with a step 2", sequence)



Zero array of 4*3 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

One unit array of size 5*4 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
rray filled with 5 of size 6*4 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

 An Array filled with random values in between 0-1, of size 2*3 [[0.93672519 0.22118957 0.05465685]
 [0.94101484 0.46716896 0.13928124]]

 Sequence array beginning from 0 to 10(excluded), with a step 2 [0 2 4 6 8]


# Vector, Matrices and Tensor

Vector: 1D array
Matrix: 2D array
Tensors: Multidimensional Array (>=3D)

All are declared using np.array([])

## Properties of Arrays
- .shape: gives you the dimensions, of the array : m,n
- .size: Returns the Total number of Elements in the Numpy Array
- .ndim: Gives the dimension of Array: 2D -> 2, 3D -> 3
- .dtype: THe Data type of 

In [11]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,True]])
arr3 = np.array([
    [ [1,2,3] ],
  [[4,5,6]],
  [[7,8,9] ],
])
print("Shape: ",arr.shape) # gives you the dimensions, of the array : m,n
print("Number of elements: ",arr.size)
print("Dimension of the Array: ",arr.ndim)
print("Data type: ", arr.dtype)
print("Third Dim",arr3.ndim)

Shape:  (3, 3)
Number of elements:  9
Dimension of the Array:  2
Data type:  int64
Third Dim 3


## Array Reshaping

### Array Reshaping in NumPy

Reshaping is the process of changing the dimensions of an array while preserving its data. The total number of elements in the new shape must equal the number of elements in the original array. For example, an array with 12 elements can be reshaped into a 3x4 or 2x6 matrix, but not a 3x5 matrix.

- np.reshape((m,n)): This function returns a new array with the specified shape. The original array remains unchanged.

- np .T / .transpose(): These are used to transpose an array, which means swapping rows and columns. It's a highly efficient operation that returns a view of the original array.

- np.flatten()`**: This method returns a 1D copy of the array. Changes to the new array do not affect the original.

- np.ravel(): This method returns a 1D view of the array whenever possible. Since it is a view, any changes made to the raveled array may also change the original array.

- np.resize() : This function changes the shape and can change the number of elements. If the new shape is larger, it pads with zeros. If smaller, it truncates the data. This is an important distinction from reshape().

- np.squeeze(): This function removes dimensions of size one. For example, an array with shape (10, 1, 5) would become (10, 5).

- np.expand_dims() / np.newaxis:  These add a new dimension of size one to the array. They are useful for ensuring arrays are compatible for operations like broadcasting. np.newaxis is a convenient shorthand used within array indexing.

- np.concatenate(): This function joins a sequence of arrays along a specified axis to form a single, larger array.

In [5]:
arr = np.arange(12)
print("",arr)

reshaped = arr.reshape((3,4)) ## We cannot have the product (m,n) be less than or more than the value
print("\nReshaped the 1D array into (3,4): \n",reshaped)

flatten = reshaped.flatten()
print("\nFlattened the reshaped: ",flatten)

# ravel() returns view instead of copy
raveled = reshaped.ravel()
print("\nRavelled the reshaped: ",raveled)

# .T -> transposes the matrix
transposed = reshaped.T
print("\nThe transposed matrix: \n",transposed)


 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped the 1D array into (3,4): 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened the reshaped:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Ravelled the reshaped:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

The transposed matrix: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]



- `axis = 1` : Rows , adds up the values of a row into one, left to right.
- `axis = 0` : Column, adds up the values of a column into one, upar se neeche, top to bottom