# Operations on Numpy Arrays

1. Slicing:
   1. Basic slicing
      1. arr[a:b]
      2. arr[:b]
      3. arr[a:]
   2. With step
      1. arr[a:b:c] : from index a to index b with step of c number of indices
2. Negative indexing: works only on 1D array, how will it work on Multidimensional arrays


1. 2D slicing
   1. arr[row_index, column_index]
   2. arr[:,:2] => means that all the rows, 

In [2]:
import numpy as np
#               0 1 2 3 4 5 6 7 8  
arr = np.array([1,2,3,4,5,6,7,8,9])
print("arr:", arr)

arr1 = arr[:2]
print("arr[:2]", arr1)

arr2 = arr[3:]
print("arr[3:]:", arr2)

arr3 = arr[4:8]
print("arr[4:8]", arr3)

arr4 = arr[1:8:2]
print("arr[1:8:2]:",arr4) # from index 1 to index 8-1 including the first and excluding the last mention

print("arr[-3]: ", arr[-3])

arr: [1 2 3 4 5 6 7 8 9]
arr[:2] [1 2]
arr[3:]: [4 5 6 7 8 9]
arr[4:8] [5 6 7 8]
arr[1:8:2]: [2 4 6 8]
arr[-3]:  7


In [3]:
arr_1d = np.array([1,2,3,4,5,6])
arr_2d = arr_1d.reshape(2,3)
print("\nEntire array:\n",arr_2d)
# specific element
print("\nelement in 2nd row 3rd column:",arr_2d[1][2])
# entire Row
print("\nThe entire first row",arr_2d[0])
# entire column
print("\nThe entire 2nd column",arr_2d[:,1])


Entire array:
 [[1 2 3]
 [4 5 6]]

element in 2nd row 3rd column: 6

The entire first row [1 2 3]

The entire 2nd column [2 5]


## Sorting

In [4]:

arr = np.array([3, 5, 1, 19, 4, 0])
sorted  = np.sort(arr)
print("\nThe unsorted Array:", arr)
print("\nThe sorted Array: ", sorted)


arr_2d_unsorted = arr.reshape((2,3))
print("\n2D unsorted array: \n",arr_2d_unsorted)
arr_2d_sorted = np.sort(arr_2d_unsorted, axis=0)

print("\naxis = 0: \n", arr_2d_sorted)
print("\n axis = 1: \n",np.sort(arr_2d_unsorted, axis=1))




The unsorted Array: [ 3  5  1 19  4  0]

The sorted Array:  [ 0  1  3  4  5 19]

2D unsorted array: 
 [[ 3  5  1]
 [19  4  0]]

axis = 0: 
 [[ 3  4  0]
 [19  5  1]]

 axis = 1: 
 [[ 1  3  5]
 [ 0  4 19]]


## Filter

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers%2 == 0]
print(even_numbers)




[ 2  4  6  8 10]


## Filter with mask

In [6]:
condition = numbers > 5 #storing expression with an evaluation.
print("Numbers greater than 5: ", numbers[condition])

Numbers greater than 5:  [ 6  7  8  9 10]


## Numpy fancy indexing vs np.where()

In [7]:

numbers = np.array([1,2,3,4,5,6,7,8,9,10])

indices = [0, 2, 4]
print("numbers at indices[0,2,4] positions",numbers[indices]) # returns the values at indices positions
where_result = np.where(numbers > 5) 

print(numbers)
print("np.where(numbers > 5): returns the indices ka array",where_result)
print("\n\n\n\nhaahahahahaha:", numbers[where_result])


condition_array = np.where(numbers > 5, numbers*2, numbers)
t_f_array = np.where(numbers > 5, True, False)
# returns the entire numbers array with the elements which are >5 being multiplied by 5
# np.where(condition, if true then return this, if not return this )
print(condition_array)
print("Put true where more than 5::: ",t_f_array)
print(numbers)



numbers at indices[0,2,4] positions [1 3 5]
[ 1  2  3  4  5  6  7  8  9 10]
np.where(numbers > 5): returns the indices ka array (array([5, 6, 7, 8, 9]),)




haahahahahaha: [ 6  7  8  9 10]
[ 1  2  3  4  5 12 14 16 18 20]
Put true where more than 5:::  [False False False False False  True  True  True  True  True]
[ 1  2  3  4  5  6  7  8  9 10]


### Adding and removing Data

- np.concatenate((a,b)): combines a and b into one new array, and returns it

In [8]:
import numpy as np
arr1 = np.array([1,2,4,8])
arr2 = np.array([4,6,34,13])

combined  = np.concatenate((arr1, arr2))
print("arr1 and arr2 concatenated",combined)
print("arr1+arr2:",arr1+arr2)

arr1 and arr2 concatenated [ 1  2  4  8  4  6 34 13]
arr1+arr2: [ 5  8 38 21]


### Compatibility handling

In [9]:
arr1 = np.array([1,2,34,5])
arr2 = np.array([1,2])
print("Compatibility check: ", arr1.shape == arr2.shape)

Compatibility check:  False


## Adding and deleting

- np.vstack((original_arr, new_row))
- np.hstack((original_arr, new_column))
- np.delete

In [20]:
original_arr = np.array([[1,2,3],[4,5,6]])
new_row = np.array([10,11,12]) 
new_col = np.array([[23],[19]])
with_new_row = np.vstack((original_arr, new_row))
# hstack: new columns
# vstack: new row
print("\noriginal_arr: \n",original_arr)
print("\n row to add : ", new_row)
print("\n with new row: \n", with_new_row)
print("\nWith new Column:\n", np.hstack((original_arr, new_col)))


deleted = np.delete(original_arr, 0, axis=1)
print("\ndeleted 2 from og array: \n", deleted)


original_arr: 
 [[1 2 3]
 [4 5 6]]

 row to add :  [10 11 12]

 with new row: 
 [[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]

With new Column:
 [[ 1  2  3 23]
 [ 4  5  6 19]]

deleted 2 from og array: 
 [[2 3]
 [5 6]]
